// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS4Et_dD3VIAN1ZiDiDMQsC2GE18vdSq4',
    appId: '1:878922015590:web:675a7c87e0802abceb1ea7',
    messagingSenderId: '878922015590',
    projectId: 'blue---rentacar',
    authDomain: 'blue---rentacar.firebaseapp.com',
    storageBucket: 'blue---rentacar.appspot.com',
    measurementId: 'G-ECKE7M61PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIO_6BGYWQ0_04tBVPJVNNtMtWzRynfSk',
    appId: '1:878922015590:android:1e19caaf34280ca6eb1ea7',
    messagingSenderId: '878922015590',
    projectId: 'blue---rentacar',
    storageBucket: 'blue---rentacar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3s_dDTZwRvoiMYbZXeCxHuvgIUbXZOcA',
    appId: '1:878922015590:ios:afc1850dfe2c1ce4eb1ea7',
    messagingSenderId: '878922015590',
    projectId: 'blue---rentacar',
    storageBucket: 'blue---rentacar.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3s_dDTZwRvoiMYbZXeCxHuvgIUbXZOcA',
    appId: '1:878922015590:ios:68d3226ddda32d58eb1ea7',
    messagingSenderId: '878922015590',
    projectId: 'blue---rentacar',
    storageBucket: 'blue---rentacar.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
